//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Entery
    {
        public int id { get; set; }
        public string description { get; set; }
        public string create_data { get; set; }
        public string amount { get; set; }
        public int bond_number { get; set; }
        public string certifying_body { get; set; }
        public string notice { get; set; }
        public string name_person { get; set; }
        public int create_by { get; set; }
        public System.DateTime date { get; set; }
    }
}
